### ISSUE TITLE
Should we try mutant?

### ISSUE THREAD

**Issue by utkarsh2102** [utkarsh2102/rubocop-packaging#36]
Hey,

I am inclined towards giving a shot to using [mutant](https://github.com/mbj/mutant).
What do you think? Should we do it, should we not?

I'd love to know your opinions on this! :)

**Comment by mvz** [comment]
Here are some thoughts:
- Trying out mutant locally is great and gives a lot of insight in where your code is untested or overly complicated.
- Current mutant is not under an open license anymore so you would be adding a non-open (development) dependency to your project.
- The last mutant released under an open license did not have many configuration options. If you don't like the style of code that it pushes you toward, you're out of luck.

**Comment by utkarsh2102** [comment]
Those are some really good thoughts, @mvz, thank you! 😄 

> Current mutant is not under an open license anymore so you would be adding a non-open (development) dependency to your project.

This would be a big problem for us then :/
So I guess we're pretty clear about this :P 

> The last mutant released under an open license did not have many configuration options. If you don't like the style of code that it pushes you toward, you're out of luck.

Aah, I see. Again, pretty clear now. Thanks for your thoughts, again! ❤️
