### ISSUE TITLE
README link is broken

### ISSUE THREAD

**Issue by ekampp** [utkarsh2102/rubocop-packaging#9]
When I go to [this link](https://wiki.debian.org/Teams/Ruby/RubyExtras/UpstreamDevelopers) from the README I'm presented with this.

![Screen Shot 2020-08-12 at 14 25 19](https://user-images.githubusercontent.com/40206/90014601-ab4fbc00-dca7-11ea-8342-ca7eddaf75af.png)

I realize that some information regarding development is nice to have behind a login. But the links in a readme for OOS software should preferably be publically accessible?

**Comment by utkarsh2102** [comment]
Hi @ekampp,

That is weird, I can't reproduce that. I can even open this in an incognito/private window.
And it needs no access or login. It's a wiki, which is open for everyone to see!

I am not entirely sure why you're getting this? :disappointed: 
Maybe try in an incognito/private window or something?

**Comment by ekampp** [comment]
Hi @utkarsh2102, I tried an incognito window. No change. 

This is FFs developer tools overview of the req/res.

![Screen Shot 2020-08-12 at 15 44 47](https://user-images.githubusercontent.com/40206/90022490-e3a8c780-dcb2-11ea-95b5-ac5555b51578.png)

**Comment by ekampp** [comment]
Also, here is the cURL:

```curl https://wiki.debian.org/Teams/Ruby/RubyExtras/UpstreamDevelopers
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>403 Forbidden</title>
<h1>Forbidden</h1>
<p>&lt;p&gt;You are not allowed to access this!&lt;/p&gt;</p>
```

**Comment by utkarsh2102** [comment]
Oh wow, this gets interesting!

cURL'ing works fine for me:
```
➜  tmp curl https://wiki.debian.org/Teams/Ruby/RubyExtras/UpstreamDevelopers
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="X-UA-Compatible" content="IE=Edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="shortcut icon" href="/htdocs/favicon.ico">
<script type="text/javascript" src="/htdocs/bugstatus.js"></script>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8">
<meta name="robots" content="index,nofollow">

<title>Teams/Ruby/RubyExtras/UpstreamDevelopers - Debian Wiki</title>
<script type="text/javascript" src="/htdocs/common/js/common.js"></script>

<script type="text/javascript">
<!--
var search_hint = "Search";
//-->
</script>


<link rel="stylesheet" type="text/css" charset="utf-8" media="all" href="/htdocs/debwiki/css/common.css">
<link rel="stylesheet" type="text/css" charset="utf-8" media="screen" href="/htdocs/debwiki/css/screen.css">
<link rel="stylesheet" type="text/css" charset="utf-8" media="print" href="/htdocs/debwiki/css/print.css">
<link rel="stylesheet" type="text/css" charset="utf-8" media="projection" href="/htdocs/debwiki/css/projection.css">
<link rel="stylesheet" type="text/css" charset="utf-8" media="all" href="/htdocs/debian-wiki-1.0.css">

and so on...
```

and here's the screenshot from a private window:

![image](https://user-images.githubusercontent.com/31288318/90024858-02b75180-dcd3-11ea-9858-88f0a87cf16f.png)

---

I am not really sure why you get this, so I'm CCing a couple of other people so we get more eyes on this issue:
@terceiro, @deivid-rodriguez, could you reproduce this? Any clue what's wrong?

**Comment by utkarsh2102** [comment]
@ekampp, just to be sure that this is nothing specific with just this Ruby page,
do you get the same while trying to access https://wiki.debian.org/Javascript/?

Should be somewhat like this:

![image](https://user-images.githubusercontent.com/31288318/90025267-82ddb700-dcd3-11ea-912c-88d07ce07d3e.png)

**Comment by utkarsh2102** [comment]
Aha, I got these:

- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=885433
- And at https://wiki.debian.org/DebianWiki/Contact#visitors:
![image](https://user-images.githubusercontent.com/31288318/90025626-f7185a80-dcd3-11ea-928f-137d7bfaab6d.png)

**Comment by utkarsh2102** [comment]
Hi @ekampp,

It looks like a much bigger netblock was blocked due to spam reasons. And I am sorry your IP was a part of this. I'll contact the wiki admins about this!
Could you please tell me your IP so I can start prodding?

**Comment by ekampp** [comment]
@utkarsh2102, I regularly use a VPN, and when I don't my IP is dynamically assigned split between two different ISPs. So unfortunately the short answer to that is unfortunately not. 

> do you get the same while trying to access https://wiki.debian.org/Javascript/?

Yes, this one looks correct.

**Comment by utkarsh2102** [comment]
> I regularly use a VPN, and when I don't my IP is dynamically assigned split between two different ISPs. So unfortunately the short answer to that is unfortunately not.

Okay, fair enough! So what I'll do is forward this issue link to Steve and Paul (Debian WiKi admins) and we'll (hopefully!) figure out a way here! :smile:

**Comment by utkarsh2102** [comment]
Hi @ekampp,

> Okay, fair enough! So what I'll do is forward this issue link to Steve and Paul (Debian WiKi admins) and we'll (hopefully!) figure out a way here! :smile: 

Could I have your email ID? I'd CC you to the thread so in case they've got something particular to ask, you'll be looped in!

**Comment by ekampp** [comment]
It's emil@kampp.me

**Comment by utkarsh2102** [comment]
Hi @ekampp,

So I've fixed this for once and for all by replacing the wiki link.
The documentation can now be found on https://github.com/utkarsh2102/packaging-style-guide

Please let me know in case you've any problems or anything! 😄
